app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
app/src/main/java/protect/card_locker/MainActivity.java

Please review the edits that I made in fixing issue #72

Fix Issue #72

---

fastlane/metadata/android/de/full_description.txt
fastlane/metadata/android/de/short_description.txt

As discussed, here come the German summary & description. Based on the English one, not just "taken literally" but adjusted a little. Note that I'm using the predecessor for a couple of years already and happily at that – so I couldn't resist the one pun with plastic cards converting your briefcase into a balloon (literally: "feels like being 5 metres thick") :wink:

Fastlane: add German summary/description

---

CHANGELOG.md

Fixes some [markdownlint](https://github.com/DavidAnson/markdownlint) issues.
- [MD004 - Unordered list style](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md004)
- [MD009 - Trailing spaces](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md009)
- [MD012 - Multiple consecutive blank lines](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md012)
- [MD032 - Lists should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md032)
- [MD034 - Bare URL used](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034)
- [MD041 - First line in file should be a top level heading](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md041)

Fix some markdownlint issues

---

app/src/test/java/protect/card_locker/ImportExportTest.java

Update csv filename

---

CHANGELOG.md
app/src/main/java/protect/card_locker/DBHelper.java
app/src/main/java/protect/card_locker/DataFormat.java
app/src/main/java/protect/card_locker/ImportExportActivity.java
app/src/main/java/protect/card_locker/ImportExportTask.java
app/src/main/java/protect/card_locker/importexport/CsvDatabaseExporter.java
app/src/main/java/protect/card_locker/importexport/CsvDatabaseImporter.java
app/src/main/java/protect/card_locker/importexport/DatabaseExporter.java
app/src/main/java/protect/card_locker/importexport/DatabaseImporter.java
app/src/main/java/protect/card_locker/importexport/MultiFormatExporter.java
app/src/main/java/protect/card_locker/importexport/MultiFormatImporter.java
app/src/main/java/protect/card_locker/importexport/VoucherVaultImporter.java
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml
app/src/test/java/protect/card_locker/ImportExportTest.java

Another loyalty card / voucher app: https://github.com/tim-smart/vouchervault
Voucher Vault issue: https://github.com/tim-smart/vouchervault/issues/4

Create Voucher Vault import code and test

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/preferences/Settings.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

Added option to keep the screen on

---

CHANGELOG.md
app/src/main/java/protect/card_locker/DBHelper.java
app/src/main/java/protect/card_locker/ImportURIHelper.java
app/src/main/java/protect/card_locker/LoyaltyCard.java
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/importexport/CsvDatabaseImporter.java
app/src/main/java/protect/card_locker/importexport/FidmeImporter.java
app/src/main/java/protect/card_locker/importexport/VoucherVaultImporter.java
app/src/main/res/layout/loyalty_card_edit_activity.xml
app/src/main/res/values/strings.xml
app/src/test/java/protect/card_locker/DatabaseTest.java
app/src/test/java/protect/card_locker/ImportExportTest.java
app/src/test/java/protect/card_locker/ImportURITest.java
app/src/test/java/protect/card_locker/LoyaltyCardCursorAdapterTest.java
app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java
app/src/test/java/protect/card_locker/MainActivityTest.java

Support setting a different barcode value than card ID

---

fastlane/metadata/android/en-US/full_description.txt
fastlane/metadata/android/en-US/short_description.txt
fastlane/metadata/android/en-US/title.txt

The current tally is 6 languages in fastlane, and 17 for the app.
In itself quite backwards. Getting the impression that it isn't available in a language it has translations for is not optimal.
Been reading up on ASO and other similar descriptions.
I think most keywords are in, but emojis are supposedly good (and that isn't my strong suit).
Keywords: F-Droid (Illegal?)
Possible emojis: Something friendly, lists, recycling symbol?
Edit: I actually considered "environmental minimalism", which I think is the queue to put my advertising-self on break.

Fastlane ASO

---

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java

Fix active tab lost on rotation

---

fastlane/metadata/android/en-US/short_description.txt
fastlane/metadata/android/en-US/title.txt

Shorter title and description

---

CHANGELOG.md
app/src/main/java/protect/card_locker/BarcodeImageWriterTask.java
app/src/main/java/protect/card_locker/BarcodeSelectorActivity.java
app/src/main/res/layout/barcode_selector_activity.xml

Was supported in ZXING for a while but never added to Catima.
Fixes #252.

Add UPC-E support

---

app/build.gradle
app/src/main/java/protect/card_locker/BarcodeSelectorActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/ShortcutHelper.java
app/src/main/java/protect/card_locker/SimpleTextWatcher.java
app/src/main/java/protect/card_locker/Utils.java
app/src/main/java/protect/card_locker/preferences/SettingsActivity.java
build.gradle

- Update NumberPickerPreference 1.0.2 -> 1.0.3 ([changelog](https://github.com/invissvenska/NumberPickerPreference/releases))
- Create stub implementation of TextWatcher so we can get rid of unused stuff
- Use AndroidX ExifInterface as recommended by Android Studio ([Release docs](https://developer.android.com/jetpack/androidx/releases/exifinterface))
- Utilize ShortcutInfoCompat (does checks internally)
- Utilize ActivityCompat.recreate (see [here](https://developer.android.com/reference/kotlin/androidx/core/app/ActivityCompat#recreate) and [here](https://developer.android.com/jetpack/androidx/releases/core#1.5.0))

Some cleanup and compatibility stuff

---

app/src/main/java/protect/card_locker/DBHelper.java

Refactored DBHelper

---

CHANGELOG.md
app/src/main/java/protect/card_locker/AboutActivity.java
app/src/main/java/protect/card_locker/BarcodeSelectorActivity.java
app/src/main/java/protect/card_locker/CardShortcutConfigure.java
app/src/main/java/protect/card_locker/CatimaAppCompatActivity.java
app/src/main/java/protect/card_locker/GroupCursorAdapter.java
app/src/main/java/protect/card_locker/ImportExportActivity.java
app/src/main/java/protect/card_locker/LoyaltyCard.java
app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardLockerApplication.java
app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/ManageGroupsActivity.java
app/src/main/java/protect/card_locker/ScanActivity.java
app/src/main/java/protect/card_locker/ShortcutHelper.java
app/src/main/java/protect/card_locker/Utils.java
app/src/main/java/protect/card_locker/preferences/Settings.java
app/src/main/java/protect/card_locker/preferences/SettingsActivity.java
app/src/main/res/drawable/active_dot.xml
app/src/main/res/drawable/ic_baseline_arrow_left_24.xml
app/src/main/res/drawable/ic_baseline_arrow_right_24.xml
app/src/main/res/drawable/inactive_dot.xml
app/src/main/res/layout/loyalty_card_view_layout.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java

Fixes #374.
I kinda like the general feel of this, because it actually makes it fall back to the card images if there is no barcode, improves consistency and makes it easier to figure out you can fullscreen the images too, but the buttons right now look just horrible...
Need some design help with this :)
https://user-images.githubusercontent.com/1885159/132256351-ccdb15a0-67a3-4285-945e-34c1b51a9c6b.mp4

Show first image as main

---

CHANGELOG.md
app/src/main/java/protect/card_locker/DBHelper.java
app/src/test/java/protect/card_locker/DatabaseTest.java

Implement FTS

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/Utils.java
app/src/main/res/xml/file_provider_paths.xml
app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java

@waffshappen suggested https://github.com/Yalantis/uCrop
targets #372
https://user-images.githubusercontent.com/22017945/139484703-e33a5da8-ccb5-4d6a-b70c-3325e34fcec9.mp4

#372 image rotation and crop

---

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java

header color is only change after an icon is set
cropper offers 1:1 by default instead when an icon is getting cropped

offer 1:1 by default when cropping icon, set header color only for icon

---

app/src/main/res/values/styles.xml

use daynight theme for toolbar

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/Utils.java
app/src/main/res/layout/loyalty_card_view_layout.xml
app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java

using icon on card view headers

---

app/src/main/java/protect/card_locker/BarcodeSelectorActivity.java
app/src/main/java/protect/card_locker/BarcodeSelectorAdapter.java
app/src/main/java/protect/card_locker/CatimaBarcodeWithValue.java
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/res/layout/barcode_layout.xml
app/src/main/res/layout/barcode_selector_activity.xml

Should make #592 easier to implement.

Cleanup barcode selector

---

app/src/main/java/protect/card_locker/ImportExportActivity.java
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/ScanActivity.java

redoing #470
currently spotBug complains about an InputStream is not being closed properly, which it didn't catch before the refactoring
I'd suggest moving opening an inputStream inside the import thread

Replaced StartActivityForResult with ResultLaunchers

---

app/src/main/res/layout/about_activity.xml
app/src/main/res/values/strings.xml

I hope that this PR fixes issue #652 :)

Add translation platform details in about page

---

app/src/main/java/protect/card_locker/ManageGroupActivity.java

Add long press to add card to group

---

app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
app/src/main/res/drawable/ic_starred_black.xml
app/src/main/res/drawable/ic_unstarred_black.xml
app/src/main/res/layout/loyalty_card_layout.xml
app/src/test/java/protect/card_locker/LoyaltyCardCursorAdapterTest.java

please review, for #635 and #619
https://user-images.githubusercontent.com/22017945/145800150-b3afa43e-de80-4172-bbdd-5d06af6276d1.mp4

635 android 5 stuck row height, 619 star icon color

---

app/src/main/java/protect/card_locker/CatimaAppCompatActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java

674 currency symbol order fixes

---

app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
app/src/main/res/layout/loyalty_card_layout.xml

681 fix star icon vector graphics, star color by theme when selected

---

app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/preferences/SettingsActivity.java
app/src/main/res/values/settings.xml

#671, #672 please review
added #607

671 adding English to list of languages, 672, 607 relaunch main activity after language, theme change

---

app/src/main/java/protect/card_locker/CardShortcutConfigure.java
app/src/main/java/protect/card_locker/CardsOnPowerScreenService.java
app/src/main/java/protect/card_locker/DBHelper.java
app/src/main/java/protect/card_locker/GroupCursorAdapter.java
app/src/main/java/protect/card_locker/ImportExportTask.java
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/ManageGroupActivity.java
app/src/main/java/protect/card_locker/ManageGroupCursorAdapter.java
app/src/main/java/protect/card_locker/ManageGroupsActivity.java
app/src/main/java/protect/card_locker/ShortcutHelper.java
app/src/main/java/protect/card_locker/importexport/CatimaExporter.java
app/src/main/java/protect/card_locker/importexport/CatimaImporter.java
app/src/main/java/protect/card_locker/importexport/Exporter.java
app/src/main/java/protect/card_locker/importexport/FidmeImporter.java
app/src/main/java/protect/card_locker/importexport/Importer.java
app/src/main/java/protect/card_locker/importexport/MultiFormatExporter.java
app/src/main/java/protect/card_locker/importexport/MultiFormatImporter.java
app/src/main/java/protect/card_locker/importexport/StocardImporter.java
app/src/main/java/protect/card_locker/importexport/VoucherVaultImporter.java
app/src/test/java/protect/card_locker/DatabaseTest.java
app/src/test/java/protect/card_locker/ImportExportTest.java
app/src/test/java/protect/card_locker/ImportURITest.java
app/src/test/java/protect/card_locker/LoyaltyCardCursorAdapterTest.java
app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java
app/src/test/java/protect/card_locker/MainActivityTest.java
app/src/test/java/protect/card_locker/TestHelpers.java

Should fix #661 
Supersedes #678 
While #678 does fix the issue too, the real issue was that an importer could cause such a state issue. So I've instead been seriously cleaning up. While all the tests pass, I do want to test this slightly longer before merging it into master.

Cleanup DBHelper

---

app/build.gradle

This should fix https://github.com/CatimaLoyalty/Android/issues/636!

Update to 2.2.8 version of ucrop!

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java

#803
this is a finicky one, please test if this commit fixes it

#803 cardView appbar icon fix

---

app/src/main/res/layout/loyalty_card_edit_activity.xml

proper clipping for card icon inside edit view

---

app/src/main/java/protect/card_locker/CardShortcutConfigure.java
app/src/main/java/protect/card_locker/LetterBitmap.java
app/src/main/res/layout/simple_toolbar_list_activity.xml

emoji icons, color theme in short-cut selection menu

---

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/Utils.java
app/src/main/java/protect/card_locker/importexport/StocardImporter.java
app/src/main/res/raw/stocard_stores.csv
app/src/test/java/protect/card_locker/ImportExportTest.java

Stocard import fixes

---

app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
app/src/main/res/drawable/ic_done.xml
app/src/main/res/layout/loyalty_card_layout.xml
app/src/main/res/values/colors.xml

**(1) There was a layout on the top of the card, I removed it
(2) I added a new selected color to the colors.xml file.
(3) Change the color of the tick mark icon from black to white.**
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated …

Added new look to selected card 

---

app/src/main/res/drawable/ic_launcher_monochrome.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml

monochrome icon

---

app/src/main/java/protect/card_locker/AboutActivity.java
app/src/main/res/values-bg/strings.xml
app/src/main/res/values/strings.xml

Fixes #984
I tested it by running emulators with different API versions and disabling the default web browser. Tested on Android 8.1, 12 and 13.
Signed-off-by: Alexander Ivanov <vanogrid@gmail.com>

Fix a crash when there's no web browser installed

---

CHANGELOG.md
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/ManageGroupActivity.java
app/src/main/res/layout/content_main.xml
app/src/main/res/menu/main_menu.xml
app/src/main/res/values/strings.xml
app/src/test/java/protect/card_locker/MainActivityTest.java

Fixes #948 
As suggested by @Altonss

Put archive link below card list

---

app/src/main/java/protect/card_locker/DBHelper.java
app/src/main/java/protect/card_locker/LoyaltyCard.java
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/test/java/protect/card_locker/DatabaseTest.java

Always update last used when creating or editing a card

---

app/src/main/java/protect/card_locker/AboutActivity.java
app/src/main/res/xml/locales_config.xml

have updated the library in the about me activity
issue #1002

library added to about me java file

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/Utils.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/file_provider_paths.xml

Enhances the app by fixing #980

View photos in gallery when Long Pressed

---

app/build.gradle
app/config/spotbugs/exclude.xml
app/lint.xml
app/src/main/java/protect/card_locker/AboutActivity.java
app/src/main/java/protect/card_locker/BarcodeSelectorActivity.java
app/src/main/java/protect/card_locker/BarcodeSelectorAdapter.java
app/src/main/java/protect/card_locker/CardShortcutConfigure.java
app/src/main/java/protect/card_locker/GroupCursorAdapter.java
app/src/main/java/protect/card_locker/ImportExportActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/ManageGroupActivity.java
app/src/main/java/protect/card_locker/ManageGroupsActivity.java
app/src/main/java/protect/card_locker/ScanActivity.java
app/src/main/java/protect/card_locker/preferences/SettingsActivity.java
app/src/main/res/layout/archive_activity.xml
app/src/main/res/layout/main_activity.xml
app/src/main/res/layout/manage_groups_activity.xml
build.gradle
settings.gradle

This PR:
- Migrates to new plugins and dependency management system
- Switches to new SDK Int only properties
- Drops buildToolsVersion as it defaults to compileSdkVersion
- Enable view binding
- Switches to a dedicated lint config

Misc Gradle improvements

---

app/src/main/java/protect/card_locker/AboutActivity.java
app/src/main/java/protect/card_locker/ImportExportActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/ManageGroupActivity.java
app/src/main/java/protect/card_locker/ManageGroupsActivity.java

This PR:
- Migrates from AlertDialog to MaterialAlertDialog
- Adds a bit spacing in new group creation dialog

Alert dialog improvements

---

app/src/main/java/protect/card_locker/ManageGroupsActivity.java

Real-time validation help, feels much better I think:

Improve group name validation flow

---

app/src/main/java/protect/card_locker/MainActivity.java

Introduced in https://github.com/CatimaLoyalty/Android/pull/1078

Fix crash on cancelling ScanActivity

---

settings.gradle

Add limitation for jitpack maven repository

---

app/src/main/java/protect/card_locker/ZipUtils.java
app/src/main/java/protect/card_locker/importexport/CatimaImporter.java

should be more efficient this way

Refactor Importer to not read entire file as String

---

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/ScanActivity.java

Add support to pick image from content provider

---

build.sh
docs/README.md

Add script to build reproducibly

---

CHANGELOG.md
app/build.gradle
app/src/main/AndroidManifest.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
lint.xml

Thank you @dependabot for not notifying for any of these. It's appreciated (ugh).

Update all libraries

---

app/src/test/java/protect/card_locker/ImportExportTest.java
app/src/test/res/protect/card_locker/catima_v1_empty_colors.csv
app/src/test/res/protect/card_locker/catima_v1_invalid_colors.csv
app/src/test/res/protect/card_locker/catima_v1_invalid_starred_field.csv
app/src/test/res/protect/card_locker/catima_v1_invalid_starred_field_2.csv
app/src/test/res/protect/card_locker/catima_v1_no_barcode_type.csv
app/src/test/res/protect/card_locker/catima_v1_no_colors.csv
app/src/test/res/protect/card_locker/catima_v1_no_starred_field.csv
app/src/test/res/protect/card_locker/catima_v1_starred_field.csv
app/src/test/res/protect/card_locker/catima_v2.csv
app/src/test/res/protect/card_locker/vouchervault.json

They should've been files from the start, because you import files, not text string.

Move all import unit test strings to their own files

---

CHANGELOG.md
app/src/main/java/protect/card_locker/CardShortcutConfigure.java
app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/ManageGroupActivity.java
app/src/main/java/protect/card_locker/Utils.java
app/src/main/res/drawable/baseline_visibility_24.xml
app/src/main/res/layout/loyalty_card_layout.xml
app/src/main/res/menu/archive_menu.xml
app/src/main/res/menu/card_details_menu.xml
app/src/main/res/menu/main_menu.xml
app/src/main/res/values/strings.xml
app/src/test/java/protect/card_locker/MainActivityTest.java

Fixes #1344
TODO:
Might not be the best way to do this, but it's 1:40AM now, so I'm going to sleep first.

Support selecting exactly which details to view in main view

---

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java

LoyaltyCardEditActivity: work around Currency.getSymbol() bug

---

app/src/main/java/protect/card_locker/ShortcutHelper.java

ShortcutHelper: trim after skipping missing cards

---

app/src/main/res/values-nb-rNO/strings.xml

ref 54d91dc8a173e0328a2eb005d9ffaea30a062690

revert s/Frie/Gratis/ in nb-rNO translation

---

app/src/main/java/protect/card_locker/DBHelper.java
app/src/main/java/protect/card_locker/LoyaltyCard.java
app/src/main/java/protect/card_locker/Utils.java
app/src/main/java/protect/card_locker/importexport/CatimaImporter.java
app/src/main/java/protect/card_locker/importexport/FidmeImporter.java
app/src/main/java/protect/card_locker/importexport/Importer.java
app/src/main/java/protect/card_locker/importexport/MultiFormatImporter.java
app/src/main/java/protect/card_locker/importexport/StocardImporter.java
app/src/main/java/protect/card_locker/importexport/VoucherVaultImporter.java
app/src/test/java/protect/card_locker/ImportExportTest.java

refactor importer part 1

---

app/src/test/java/protect/card_locker/ImportExportTest.java

See https://github.com/robolectric/robolectric/issues/8359

use JPGs instead of LetterBitmap b/c of partial robolectric Canvas support

---

app/src/main/java/protect/card_locker/importexport/FidmeImporter.java
app/src/main/java/protect/card_locker/importexport/StocardImporter.java
app/src/main/java/protect/card_locker/importexport/VoucherVaultImporter.java

Refactors the other importers to use a separate `saveAndDeduplicate()` function like #1422 did for the catima importer.

refactor importer part 2

---

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java

Fixes #1379.
The `onResuming`/`onRestoring` checks are needed to make sure the balance doesn't get parsed/changed before it's set to the correct value.

LoyaltyCardEditActivity: fix wrong balance parse after locale changes

---

app/src/main/res/values/settings.xml
app/src/test/java/protect/card_locker/UtilsTest.java

Better default card colours

---

app/src/main/AndroidManifest.xml
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/ManageGroupActivity.java
app/src/main/java/protect/card_locker/ManageGroupsActivity.java
app/src/main/java/protect/card_locker/preferences/SettingsActivity.java
app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java

Closes: https://github.com/CatimaLoyalty/Android/issues/1498

Migrate to from OnBackPressed to OnBackPressedDispatcher

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/Utils.java

Closes: https://github.com/CatimaLoyalty/Android/issues/917

CatimaAppCompatActivity: Set navigation bar color on Android 8.1+

---

.github/workflows/generate-feature-graphic.yml
.scripts/generate_feature_graphic/generate_feature_graphic.sh

Support translating Catima app name in feature graphic

---

app/build.gradle.kts
app/src/main/res/values/settings.xml
app/src/main/res/xml/locales_config.xml

Haven't had time to test this in the app itself, but it looks correct and makes the script work correctly too.

fixes for pt -> pt-rPT

---

.github/workflows/contributors-to-file.yml
app/src/main/java/protect/card_locker/AboutActivity.java
app/src/main/java/protect/card_locker/AboutContent.java

Only list contributors with at least 5 commits

---

CHANGELOG.md
app/build.gradle.kts

Let's just get this in in the start of a cycle so if it breaks something unknown we have fairly long to notice.
Fixes #1549

Target Android 14

---

CHANGELOG.md
app/src/main/res/layout/loyalty_card_edit_activity.xml

| - | - |
| ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/c8e564b8-d61b-4d05-b79a-f50e750926fc) | ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/a3edfbe6-ac33-4a4b-a13e-44a8b6cd271a) |
(Ignore the colour different, theming is slightly different)

Improve layout of photos tab in card edit view

---

.scripts/generate_feature_graphic/generate_feature_graphic.sh

Fix feature graphic generation 

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/MainActivity.java
app/src/main/java/protect/card_locker/ShortcutHelper.java

Several fixes for shortcut handling
- Update the card priority in the dynamic shortcut manager also when the card isn't opened from the main screen
- Remove from dynamic shortcut manager when the card gets archived
- Fix icons disappearing of other cards when one card gets removed
Fixes #1779

Several fixes for shortcut handling

---

app/src/main/java/protect/card_locker/Utils.java

In past issues, it was expressed that security could be improved regarding the PDF process. I have made some minor changes in the Util file, as a start.
These changes improve resource management and error handling while maintaining good coding practices. Firstly, I closed the resources in a finally block, to ensure they are properly released. I also made a check to validate Uri before usage, which could potentially have some additional validation in a later commit, to ensure it points to a valid PDF file. Additional minor changes are performed to handle errors and sensitive information more securely. I have performed tests to see if there is some deviation of these changes from the previous functionalities, and all appeared to be clear.

Improve Security of Barcode Retrieval from PDF

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/Utils.java

This should really fix #1775 (see comments in #1878)

Properly fix decimal separator detection logic

---

app/src/main/java/protect/card_locker/LoyaltyCard.java

This PR addresses the issue #1849 
In addition to fixing this method, some minor formatting issues in the `LoyaltyCard` class have been corrected for better readability and code style consistency.
- Updated `describeContents()` method to return `0`.
- Corrected small formatting issues (e.g., indentation, spacing) in the `LoyaltyCard` class.
- Ensured that the project compiles successfully.
- Ran existing tests to confirm that the changes do not break any functionality.

Fix describeContents() and the formatting in LoyaltyCard Class

---

CHANGELOG.md
app/src/main/AndroidManifest.xml
app/src/main/java/protect/card_locker/MainActivity.java

Support for creating a card from shared text

---

.scripts/generate_feature_graphic/generate_feature_graphic.sh

See https://github.com/CatimaLoyalty/Android/actions/runs/10673292588/job/29582116382

Fix feature graphic generation failing for languages without title.txt

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/preferences/Settings.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

Fixes #1553, closes #2100.
These are the changes in #2100 squashed into a single commit (which I couldn't do because that branch was made from the main branch) and another commit added to rephrase some settings for consistency (to ensure translators only get pinged once for new translations).
Thanks a lot for your work, @rzuhovski0!

Volume key navigation

---

app/src/main/res/layout/alertdialog_row_with_icon.xml

| - | - |
| ![Screenshot_20241028-225154_Trebuchet](https://github.com/user-attachments/assets/95465ea0-7b2b-4a25-b7ae-744d943b38c9) | ![Screenshot_20241028-225130_Trebuchet](https://github.com/user-attachments/assets/ea9727d1-23c0-4f82-9caf-f79c644ace6c) |

Fix text wrapping on add dialog

---

app/src/main/java/protect/card_locker/Utils.java

Fix parsing PDF with transparent background

---

app/src/main/java/protect/card_locker/ShortcutHelper.java

Follow-up for #2201 and #2205. Forgot the shortcuts...

Fix background colour for shortcuts

---

app/build.gradle.kts
app/src/main/res/layout/barcode_selector_activity.xml
app/src/main/res/layout/import_export_activity.xml
app/src/main/res/layout/loyalty_card_view_layout.xml
app/src/main/res/layout/scan_activity.xml

Most things seem to work fine. Just the new edge-to-edge changes are quite painful.

Android 15 (SDK 35) support

---

app/src/main/java/protect/card_locker/ScanActivity.java
app/src/main/java/protect/card_locker/Utils.java

I was working wtihout latest commit so I hope it will be buildable, let me know when it will be merged and closed tickets I can check some other bugs too.

Fix for coloured QR code fails to scan #2366

---

docs/README.md

Powered by https://shields.rbtlog.dev/

Add reproducibility status
