app/src/main/java/protect/card_locker/CsvDatabaseExporter.java, app/src/main/java/protect/card_locker/CsvDatabaseImporter.java, app/src/main/java/protect/card_locker/DBHelper.java, app/src/main/java/protect/card_locker/ImportURIHelper.java, app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java, app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/MainActivity.java, app/src/main/java/protect/card_locker/Utils.java, app/src/main/res/layout/loyalty_card_edit_activity.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/test/java/protect/card_locker/DatabaseTest.java, app/src/test/java/protect/card_locker/ImportExportTest.java, app/src/test/java/protect/card_locker/ImportURITest.java, app/src/test/java/protect/card_locker/LoyaltyCardCursorAdapterTest.java, app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java, app/src/test/java/protect/card_locker/MainActivityTest.java
Been working on improving the edit UI to get it ready for #45 and #8.
TODO:
=> Icon-friendly edit UI

.github/workflows/android.yml, app/build.gradle, app/src/main/java/protect/card_locker/preferences/SettingsActivity.java, app/src/main/res/layout/settings_activity.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
- Add gradle wrapper validation action (see [here](https://github.com/gradle/wrapper-validation-action))
- Update upload-artifact to v2 (see [here](https://github.com/actions/upload-artifact/releases))
- Update gradle wrapper to 6.8.3 using git bash
- Update AS 4.1.1 -> 4.1.3
- Update spotbugs plugin 4.6.0 -> 4.7.0 ([changelog](https://github.com/spotbugs/spotbugs-gradle-plugin/releases))
- Update Google Material 1.2.1 -> 1.3.0 ([changelog]())
- Update Guava 30.1 -> 30.1.1 ([changelog]())
- Update NumberPickerPreference 1.0.1 -> 1.0.2 ([changelog]())
- Update Test Core 1.0.0 -> 1.3.0 ([changelog]())
- Update JUnit 4.13.1 -> 4.13.2 ([changelog]())
- Use FragmentContainerView that was introduced in [1.2.0](https://developer.android.com/jetpack/androidx/releases/fragment#1.2.0-alpha02) for …
=> A few miscellaneous improvements

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/Utils.java, build.gradle
Bump targetSDK and buildtools
Bump Gradle Version
Bump Application Version
Android 11: android:exported=" must now be set in the Manifest for Intents
Enable -Xlint:deprecation default (Warn)
Replace some Deprecations:
getBitmap (Deprecated in 29) with ImageDecoder
(Tested on Emulator and Lineage 18)
getColor with ContextCompat.getColor (23 and up)
Sadly i do NOT have a real Android < 23 device to test that but works in a KitKat Emulator.
=> TargetSDK, Version Upgrades, Deprecations and XLint

app/src/main/java/protect/card_locker/CardShortcutConfigure.java, app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java, app/src/main/java/protect/card_locker/MainActivity.java
#449 
-  After removing the additional click listener in card icon, clicking the card icon itself works just like clicking in the rest of the card.
<table><tr>
<td>
<td>
</table>
=> Removed click listener from card icon

app/src/main/res/values-nb-rNO/strings.xml, fastlane/metadata/android/nb-NO/changelogs/70.txt, fastlane/metadata/android/nb-NO/changelogs/71.txt, fastlane/metadata/android/nb-NO/changelogs/72.txt, fastlane/metadata/android/nb-NO/changelogs/73.txt, fastlane/metadata/android/nb-NO/changelogs/74.txt, fastlane/metadata/android/nb-NO/changelogs/75.txt, fastlane/metadata/android/nb-NO/changelogs/76.txt, fastlane/metadata/android/nb-NO/changelogs/77.txt, fastlane/metadata/android/nb-NO/changelogs/78.txt, fastlane/metadata/android/nb-NO/changelogs/79.txt, fastlane/metadata/android/nb-NO/changelogs/80.txt, fastlane/metadata/android/nb-NO/changelogs/81.txt, fastlane/metadata/android/nb-NO/changelogs/82.txt, fastlane/metadata/android/nb-NO/changelogs/85.txt
Primarily includes translations to most of the untranslated strings (except `credits` because I've been blanking on the translation for a solid hour), several changelogs (all the way back to 70, including 85 -- just saw that's not released yet though. Also saw it's present in the english directory, so I assumed it was fine to include this), and a few changes to a couple of the existing translations for consistency, using modern or contextually accurate words, or for [a word](https://github.com/TheLastProject/Catima/commit/fb95c8c9d40bc42cc9df856679da9bd30417fbf4) that has absolutely [no record of being used like that](https://no.wikipedia.org/w/index.php?search=Gemenhetslig&title=Spesial%3AS%C3%B8k&go=G%C3%A5&ns0=1) [in any context of …
=> Additional Norwegian translations

app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java, app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/ShortcutHelper.java, app/src/main/res/layout/loyalty_card_layout.xml
adding padding to icons referencing https://developer.android.com/reference/android/graphics/drawable/AdaptiveIconDrawable.html
=> preserve shortcut icon shape by padding, getting round corners back on card lists

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
From android 5 to 9, going into full screen then back adds a top padding onto the coordinator layout bottom sheet
This aims to prevent that by removing the bottom sheet before entering full screen, then adding it back after leaving full screen
=> prevent bottomSheet from growing a padding getting into/leaving fullscreen

app/src/main/res/values/strings.xml
=> Less verbose strings

app/src/main/java/protect/card_locker/BarcodeImageWriterTask.java, app/src/main/java/protect/card_locker/CatimaBarcode.java, docs/README.md
This hopefully fixes issue #592.
It tried to scan several code 93 barcodes and it worked. Now I don't know if this breaks anything or if it is very accurate. Sometimes scanned codes are recognised in the wrong "format", but that happens with several types of codes on my phone anyway ^^
=> Add code 93

app/src/main/res/layout/content_main.xml
FIxes #764 
Added padding to the recycler view of the main list.
*Screen Preview*
=> Add padding to the bottom of the main list.

app/src/main/java/protect/card_locker/CatimaAppCompatActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/MainActivity.java, app/src/main/java/protect/card_locker/Utils.java, app/src/main/java/protect/card_locker/preferences/Settings.java, app/src/main/java/protect/card_locker/preferences/SettingsActivity.java, app/src/main/res/values-night/themes.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml, app/src/main/res/xml/preferences.xml
https://github.com/CatimaLoyalty/Android/discussions/749#discussioncomment-1991766
please review
=> various color fixes

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/ScanActivity.java, app/src/main/res/values/strings.xml
This PR contains a fix for issue #856, which concerns a crash that occurs when no activity can handle the intent to pick an image file.
* Disable all the gallery apps (e.g., Google Photos)
* Go to the ScanActivity by clicking the FAB on the home screen
* The app crashes when you click the button "Select image from gallery"
Clicking that button should have launched a gallery app, or displayed a disambiguation dialog if there is more than one app that can handle the intent being invoked.
Wrapped the call to launch in a try-catch block.
=> Crash on clicking "Add from image" button in scan activity #856

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/Utils.java
Reverts CatimaLoyalty/Android#1010
Makes the button navigation buttons pretty invisible on white theme.
=> Revert "[UI] Fix colors on navigationBarColor"

CHANGELOG.md, app/src/main/java/protect/card_locker/MainActivity.java, app/src/main/res/layout/content_main.xml, app/src/main/res/menu/main_menu.xml, app/src/test/java/protect/card_locker/MainActivityTest.java
While I much prefer the design introduced in
https://github.com/CatimaLoyalty/Android/pull/1009, it sadly caused a serious performance regression
(https://github.com/CatimaLoyalty/Android/issues/1026).
This commit restores the old behaviour so that a new release isn't blocked while this is figured out.
=> Move Archive back into overflow menu

app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
This reduces repetition in the codebase to make #1083 cleaner to implement.
This also more explicitly sets the text colour to prevent RecyclerView state bugs and thus fixes #1049.
=> Reduce repeated code in LoyaltyCardCursorAdapter

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/Utils.java
Following a discussion in #1083, it was discovered that the `DatePickerDialog` may sometimes store the expiry date at 12:00 PM instead of 12:00 AM in the DB. While this is currently not a problem visible to the user, this PR fixes it, so it doesn't cause issues in the future in case new types of dates are added (like a 'valid from' date) or we change the way the expiry date comparison works. I also added a note reminding that some expiry dates have already been stored at 12:00 PM in the DB.
=> Fix DatePickerDialog sometimes storing dates at 12 PM instead of 12 AM

app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
Fixes #1049 
It looks like `field.getTextColors().getDefaultColor()` didn't return the correct color, so the text remained red. This PR sets the text color to the same value as in `loyalty_card_layout.xml`.
=> Fix Expiry field text remaining red after the card is no longer expired

app/src/main/java/protect/card_locker/MainActivity.java, app/src/main/java/protect/card_locker/ScanActivity.java, app/src/main/res/layout/camera_permission_failed_layout.xml, app/src/main/res/layout/content_main.xml, app/src/main/res/layout/custom_barcode_scanner.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/themes.xml
Hi,
This PR closes #1092.
Change details are listed below.
* Added ` NestedScrollView ` to  ` MainActivity ` to make it scrollable when the screen space is not enough for the UI to expand.
*  Added ` NestedScrollView ` to  ` ScanActivity` to make it scrollable when the screen space is not enough for the UI to expand. 
* Screen may blink to black and soon recover when adjusting the app's window size, this will happen when dynamically adjusting app's window size in split-screen mode which most modern Android phones support.
=> Closes #1092 -  Fixed contents cut off on smaller screen issue.

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/res/values/dimens.xml
#1074
Views are expecting pixel values. Using 20 or 60 will result in different spacing per device resultion. 
Extract those values to dimens and we dont have to deal with that anymore.
=> Fix spacings in custom view of alert dialogs

app/src/main/res/values-ar/strings.xml, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el-rGR/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-in-rID/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Stocard renamed their exports to no longer contain sync, only your user id.
Also related to #1242. Sadly forgot to do this before making a new release. Oh well.
=> Fix Stocard export filenames

app/src/main/res/drawable/dialog_bg_monet.xml, app/src/main/res/layout/preference_material_switch.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml, app/src/main/res/xml/preferences.xml
This pull request fixes #1263
Switches and Dialogs in Settings don't have Material You style applied. 
- Introduced custom layout `preference_material_switch.xml` for Material 3 switch and applied it to switches in Settings
- Introduced new drawable `dialog_bg_monet.xml` that applies theme color and rounded edges to the Dialog
- Added new style `ThemeOverlay.App.MaterialAlertDialog.Monet` that applies Material 3 style (fonts and layout) and the color from the custom drawable to Dialog  for day and night themes and applied it for `materialAlertDialogTheme` and `alertDialogTheme`
- Open the app
- Go to settings, verify switches
- Tap any `ListPreference` element, verify dialog
By making a contribution to this project, I certify that:
The contribution was created in whole or in part by me …
=> Update Settings screen to use Material You design

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
This closes issue #1326
Since, dialog messages are not selectable. Therefore, I created a TextView, made it selectable, applied padding and then attached it to the dialog. I took the liberty of giving it a top padding of 16 to add some space between the title and the text.
=> Made barcode value text Selectable

app/src/main/res/layout/sorting_option.xml
Currently, the "...in reversed order" checkbox has a larger font size than the radio buttons above it. It looks cleaner to me with the font sizes matched. I don't know how the font size for the radio buttons is determined by `MaterialAlertDialogBuilder.setSingleChoiceItems()`, so I tried a few sizes and `16sp` looks identical to me.
=> make checkBox_reverse font size match sort type radio buttons

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/ManageGroupsActivity.java
Following up on https://github.com/CatimaLoyalty/Android/pull/1331#issuecomment-1574118467, this adds top padding to all dialogs. IMO it looks a bit nicer. And it's consistent :)
I didn't want to hardcode a value, but I thought the padding used for left and right was more than the top needed so I divided it by half.
<details>
<summary>screenshots</summary>
</details>
=> add top content padding to dialogs

.github/workflows/android.yml
Makes #1350 less frequent. Before, I got the stuck test about 1/7 runs. With this change I needed >20 runs to reproduce.
=> CI: use OpenJDK 17 from Ubuntu

CHANGELOG.md, app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java, app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/ShortcutHelper.java, app/src/main/java/protect/card_locker/Utils.java
Fixes #1361
- Ensure a header colour is picked for the main screen
- Simplify all different header colour code pickers into a single code path
=> Make header colour code more consistent

app/src/main/res/layout/about_activity.xml
Fixes #1362.
<details>
<summary>screenshots</summary>
</details>
=> about_activity: make _sub layout consistent (fixes RTL)

app/src/main/res/layout/sorting_option.xml
Fixes another RTL bug.
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>
=> sorting_option.xml: RTL fix

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/res/layout/loyalty_card_view_layout.xml
Fixes two more RTL bugs.
I can't figure out how to fix it so the cart and info buttons are swapped in RTL, at least not using XML only.
IMO not swapping them is fine, especially with the arrow buttons fixed now at least.
<details>
<summary>before (rtl)</summary>
</details>
<details>
<summary>after (ltr + rtl)</summary>
</details>
=> LoyaltyCardViewActivity: RTL fixes for buttons

app/src/main/java/protect/card_locker/BarcodeImageWriterTask.java
Fixes #1332.
<details>
<summary>screenshots</summary>
</details>
=> Improve barcode rendering (square codes & padding)

app/src/main/java/protect/card_locker/BarcodeImageWriterTask.java, app/src/main/java/protect/card_locker/CatimaBarcode.java
Following up on https://github.com/CatimaLoyalty/Android/pull/1359#issuecomment-1603359582: `DATA_MATRIX` can be rectangular as well.
I also removed `MAXICODE` since it's not supported.
I tested the changes on my phone. It looks slightly better than before #1359 now IMO. Square versions looked okay too.
<details>
<summary>screenshot: before</summary>
</details>
<details>
<summary>screenshot: after #1359</summary>
</details>
<details>
<summary>screenshot: with this fix</summary>
</details>
<details>
<summary>screenshot: with second commit too [Edit]</summary>
</details>
=> CatimaBarcode: DATA_MATRIX is not always square

.github/workflows/android.yml
Another attempt to handle the stuck unit test better.
=> CI: on retry, stop gradle daemon and timeout

app/src/main/AndroidManifest.xml, app/src/main/java/protect/card_locker/contentprovider/CardsContentProvider.java, app/src/main/java/protect/card_locker/preferences/Settings.java, app/src/main/java/protect/card_locker/preferences/SettingsActivity.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/test/java/protect/card_locker/ImportExportTest.java, app/src/test/java/protect/card_locker/TestHelpers.java, app/src/test/java/protect/card_locker/contentprovider/CardsContentProviderTest.java, docs/CONTENT_PROVIDER.md
Implement a simple ContentProvider that provides read-only access to the cards. This allows for external apps to read the cards and groups.
Read access is protected by the dangerous permission `me.hackerchick.catima.READ_CARDS`
Gadgetbridge PR with the matching integration (still very much a WIP for experimenting): https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/2953
Marking as draft since:
- Only for feedback / visibility for now
- Needs some docs
- Need to check if and how to create some tests
=> Introduce read-only ContentProvider for cards

app/src/main/java/protect/card_locker/ImportURIHelper.java, app/src/test/java/protect/card_locker/ImportURITest.java
Some browsers such as firefox will add a trailing slash to the path. When clicking the "Open in app" button after, Catima would fail to recognize the path.
=> Fix parse of import URI with trailing slash

app/src/main/AndroidManifest.xml, docs/CONTENT_PROVIDER.md
Fix the permission conflict introduced by #1121
Tested with a debug build of Gadgetbridge + release apk from #1410
Fixes #1410
=> Fix content provider permissions conflict

app/src/main/java/protect/card_locker/ShortcutHelper.java
I think this fixes #1413. I can't test it atm (and I can't reproduce the crash either), but I test it later.
This only fixes the NPE. A better fix would skip those cards when trimming the list as well. I can add that later as well.
Not sure if there's maybe a good way to prevent outdated cards from existing to begin with. Maybe we should clear the shortcuts after import and/or on first start; idk.
=> ShortcutHelper: skip outdated cards that no longer exist

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
Fixes #1201. When you tab in and out of other apps or rotate your screen, the `DatePickerFragment` won't cause crashes anymore.
Let me explain how the fix works:
- `Fragment`s must have a public, no arguments constructor. Any data you want to pass to them must be put in a `Bundle` for Android to be able to persist it across configuration changes (like the situations above).
- Communication between fragments or between an activity and a fragment is performed with `FragmentManager.setFragmentResultListener()` on the activity/fragment that receives the callback and `FragmentManager.setFragmentResult()` on the one that sends the callback. The callback data must fit in a `Bundle`.
In the original code, the date picker directly sets the target text field. Here, the code for setting the text …
=> Fix crash on configuration changes in DatePickerFragment

app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
Also removes a duplicate `field.setVisibility(View.VISIBLE)`.
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>
=> only show divider with name/note + extra field

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java
Fixes #1432 by making sure `updateTempState()` is always called IFF `setTag()` is (unless the tag is set using the temp state).
=> LoyaltyCardEditActivity: fix state loss on rotation for dates

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
Fixes #1461.
According to the `setColorPickerDialogListener()` documentation: 
> The preferred way to handle the callback is to have the calling `Activity` implement `ColorPickerDialogListener` as this will not survive an orientation change.
Also fixes a second bug where cancelling the color picker (by pressing the back button) would delete an existing image by moving that code to the callback instead of executing it unconditionally after showing the dialog.
=> LoyaltyCardEditActivity: fix color picker dialog crash & bug

app/build.gradle, app/src/main/java/protect/card_locker/Utils.java, app/src/main/java/protect/card_locker/preferences/SettingsActivity.java, app/src/main/res/resources.properties, build.gradle
Here's my take on #991. I tested my implementation on multiple emulators from Android 5 to 13 and everything seems to work fine (including keeping the preference and A13 system settings in sync too).
P.S: I noticed you have enabled support for Java 8+ APIs in the app via core library desugaring (which means you can freely use Java 8+ stuff without encountering compatibility problems with low Android versions)... but you aren't actually using them, which is a shame. (Java 8's `java.time` APIs are *miles* better than the legacy `Date`/`Calendar`, for instance, not to mention the functional programming potential with the Java standard library (`Stream`, `Optional`, etc.)).
=> Android 13 per app language support

PRIVACY.md, app/build.gradle, app/src/main/java/protect/card_locker/AboutActivity.java, app/src/main/java/protect/card_locker/AboutContent.java, app/src/main/java/protect/card_locker/Utils.java, app/src/main/res/raw/.gitignore, app/src/main/res/raw/license.html, app/src/main/res/values/strings.xml
Fixes #1324.
---
<details>
<summary>screenshots</summary>
</details>
=> embed history/privacy policy/license in app

app/src/main/java/protect/card_locker/ManageGroupsActivity.java
The improvements in d54a3127a6ebc1e200ce826c52944825511d6ad8 left that function unused.
=> ManageGroupsActivity: rm unused setGroupNameError()

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
Fixes #1425.
This fixes leaving the edit view returning you to the main view instead of the card view (if that's what you were on).
We need to make sure the view activity is properly updated after returning.
| Action | Working | Details |
| - | - | - |
| Press back icon | :heavy_check_mark: | |
| Press back button | :heavy_check_mark: | |
| Save after editing | :heavy_check_mark: | Fixed in 8310f096412d22ad0f8ced67d877b7061b8e43d6 |
| Edit store name | :heavy_check_mark: | |
| Edit store colour | :heavy_check_mark: | |
| Set store image | :heavy_check_mark: | |
| Remove store image | :heavy_check_mark: | |
| Change card ID | :heavy_check_mark: | |
| Change barcode type | :heavy_check_mark: | |
| Removing barcode | :heavy_check_mark:  | |
| Switching from no barcode to barcode | …
=> Return to last view after edit

app/src/main/java/protect/card_locker/MainActivity.java
The callback used by the display options menu bypassed the card counter. This used to work fine as the visible count used to remain the same but when toggling the visibility of archived cards was added to the display menu this caused the UI to get stuck with a wrong idea of how many cards are visible.
Fixes #1525
=> Fix incorrect UI updates when toggling showing archive if all cards in group are in archive

app/src/main/res/values/settings.xml
This syncs the list in `app/src/main/res/values/settings.xml` with the files in the repo, with the too low translations commented out but listed, as is the case for existing ones now.
I enabled [Vietnamese](https://hosted.weblate.org/projects/catima/catima/vi/) as it's at 95%, which seems good enough to me, especially since the issue seems to be that some terms are simply hard to translate (so it would probably have been 100% otherwise); if you really want it to be 100% before including I can disable it.
[Kannada](https://hosted.weblate.org/projects/catima/catima/kn/) is too low at 19%. [Malayalam](https://hosted.weblate.org/projects/catima/catima/ml/) too at 26%.
=> add locales: vi (enabled), kn (disabled), ml (disabled)

.gitignore, app/build.gradle.kts, app/src/debug/res/values/strings.xml, app/src/main/AndroidManifest.xml, app/src/main/java/protect/card_locker/MainActivity.java, app/src/main/res/values/strings.xml
Removes the hardcoded app_name values, removes no longer needed label and setTitle, override `app_name` in Debug build.
Also had to update the `.gitignore` as it wanted to exclude the `debug` string values. For this I created a new Android Studio project, copied over the newly generated `.gitignore` and then added a few things manually under "Android extras" that Catima seems to need.
Fixes #1539, supersedes #1566.
=> Make app title translatable

app/src/main/java/protect/card_locker/CatimaAppCompatActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/UCropWrapper.java, app/src/main/java/protect/card_locker/Utils.java
Following up on https://github.com/CatimaLoyalty/Android/pull/1547/files#r1349352117:
It seems `getWindow()` can return `null`: [the docs](https://developer.android.com/reference/android/app/Activity#getWindow()) say "The current window, or null if the activity is not visual."
I'm not entirely sure what "visual" means here (presumably not merely the same as "visible") and was unable to find out under what circumstances it can be null by searching the docs.
It seems e.g. [nextcloud added this check as well](https://github.com/nextcloud/android/pull/2225) so it seems prudent to do so just in case (and at least consistently do so instead of checking it in one place but not everywhere).
And Android doesn't actually guarantee that `onPostCreate()` runs before `onResume()`, so I also made a …
=> add null checks for getWindow()

.github/workflows/update-locales.yml, .scripts/new-locales.py
Follows up on #1499.
```diff
$ .scripts/new-locales.py
Updating...
$ git diff
diff --git a/app/src/main/res/values/settings.xml b/app/src/main/res/values/settings.xml
index ccb2204c..ee46b5f7 100644
--- a/app/src/main/res/values/settings.xml
+++ b/app/src/main/res/values/settings.xml
@@ -97,6 +97,7 @@
<item>lt</item>
<item>lv</item>
+        
<item>nb-rNO</item>
<item>nl</item>
<item>oc</item>
@@ -110,8 +111,8 @@
<item>tr</item>
<item>uk</item>
<item>vi</item>
-        <item>zh-rTW</item>
<item>zh-rCN</item>
+        <item>zh-rTW</item>
</string-array>
<string-array name="card_orientation_values">
```
=> add workflow to add new locales

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java
This PR migrates Catima to use the new MaterialDatePicker. MaterialDatePicker is already based on DialogFragment, thus drop the current fragment and use the picker directly.
- https://github.com/CatimaLoyalty/Android/issues/1516
=> LoyaltCardEditActivity: Migrate to materialdatepicker dialog

.scripts/generate_feature_graphic/generate_feature_graphic.sh
This was only needed (and suggested by `shellcheck`) w/o `set -e`.
=> generate_feature_graphic.sh: remove redundant "|| exit 1"

app/src/main/java/protect/card_locker/CatimaAppCompatActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/Utils.java
Follow-up for #1559 (marked draft as it is based on that to avoid a merge conflict).
=> Refactor navbar colour

CHANGELOG.md, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
If a card icon exists, open it in the gallery, like is done with photos.
While the intended behaviour was for users to use the card icon only as a general... icon and use the photos tab in the card edit screen to set photos, a 2 star review I just got on Google Play makes it clear some people put pictures in there they want to be able to zoom.
While the usage seems limited, as icons are quite small, a simple tap wasn't bound to anything except telling the user to long-press anyway so this was very easy to add and felt logical enough to support for consistency with photos.
=> Open card icon in gallery on touch

app/src/main/java/protect/card_locker/ScanActivity.java, app/src/main/res/values/strings.xml
Manual entry is an useful feature for when you don't have a card to access. However, some stores use a different card ID than barcode value, causing users to create cards that won't work.
While I don't want to completely remove this feature, I think it is helpful to nudge users towards scanning with the camera if possible to reduce the risk of creating cards that won't work.
This change makes it so that an extra dialog window pops up when users select the "Enter the barcode manually" option under "More options" in the scan activity:
=> Nudge users away from manual entry

CHANGELOG.md, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/res/values/strings.xml
| ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/27b92306-0ea9-45d8-affc-3b96a09d6470) | ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/f4d90413-f790-41f8-9d9f-3f0cf0f3439d) | ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/0914340a-4d8f-4e2a-b980-edaaf576c3bc) |
| - | - | - |
| Disables buttons when no amount is filled in | Enables buttons when change is valid |  Shows toast on update |
=> Update spending screen to also support receiving

app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java, app/src/main/java/protect/card_locker/Utils.java
| - | - |
| ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/4f88cd11-4369-4112-a1cb-628eee440207) | ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/9485c5ff-709c-4213-8620-79a5176600c4) |
See the small margin on the left on the "first day" logo (ignore the background colour, the debug build uses a different theme)
=> Fix background colour not being set for images in card view

app/src/main/java/protect/card_locker/ImportExportActivity.java
| Export | Import |
| - | - |
| ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/c17778da-0fb3-4656-b79b-ae36c512ebdd) | ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/16547b4a-9d43-45b7-a12d-05bc5be42dff) |
Fixes #1766
=> Make it possible to view password on export/import dialogs

docs/RELEASE_STEPS.md
AGP 8.3 includes the commit hash in the build metadata, so for the official build to be reproducible it needs to be on the same commit as third-party builds. This commit reorders the instructions to ensure I will create the commit before building and thus fixes an RB failure in AGP 8.3+.
@obfusk I heard through @IzzySoft that you found an RB failure in Catima. As I understood it, Catima 2.28.0 is not reproducible because the commit hash differs as I always build the .apk file before creating the commit (but after changing the files), right? Am I correct in understanding this should fix Catima RB?
I haven't been able to find info on this in the AGP release notes (maybe I missed it), but do you know if it also tracks the dirty state? If so I'll have to be extra careful to not have any …
=> Fix RB failure

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/Utils.java
Fixes #1775 at the cost of big values no longer being displayed as nicely (1.000.000 is now displayed as 1000000).
| | |
| - | - |
| ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/527604a5-149c-4866-809a-7598d23bab87) | ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/2ee12525-5f12-45ac-9beb-065d61e4bdcf) |
| ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/35421300-2402-471c-a613-c339937b3181) | ![image](https://github.com/CatimaLoyalty/Android/assets/1885159/c73ebf20-c791-4d72-8a42-3c75b3cb9063) |
=> Disable currency grouping and accept thousand separator as decimal separator

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/res/layout/loyalty_card_view_layout.xml, app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java
Replace the field showing the barcode ID with the text "Front image" or "Back image" when the front or back image are displayed.
As suggested on https://github.com/CatimaLoyalty/Android/issues/1889#issuecomment-2120550099.
| ---------- | ------- |
| ![Image shown with barcode below it](https://github.com/CatimaLoyalty/Android/assets/1885159/d2b2288d-a657-47dd-9b89-f486ccf37aab) | ![Image shown with text "Front image" below it](https://github.com/CatimaLoyalty/Android/assets/1885159/f5087422-f267-4401-b892-bae143ecb481)
=> Show image type on view screen when not viewing barcode

CHANGELOG.md, app/src/main/java/protect/card_locker/ImportExportActivity.java
This seems to fix Android sometimes throwing
NetworkOnMainThreadException when importing bit files through the Nextcloud app.
I'm not sure if this is necessary for the export too, but it doesn't seem to break anything so for consistency it makes sense to also wrap the exporter into a thread.
This change is suboptimal because it will still block the UI with a ProgressDialog (which is deprecated) and force the user to wait until the import/export completes (and will kill the import/export if the app gets backgrounded) but it should at least fix the most common crash for most users.
=> Run Import/Export on non-UI thread

CHANGELOG.md, app/src/main/java/protect/card_locker/Utils.java, app/src/main/res/layout/loyalty_card_layout.xml
Allowing spanning multiple lines helps in case the store name doesn't fit on a single line. However, the store name should fit a single line if possible because it looks better when the store name isn't split among lines. Due to limitations in Android's autoSizeTextType system, this needs a fairly ugly workaround.
Fixes #1961
| Before | Removing `android:maxLines="1"` on `@+id/thumbnail_text` without other changes  (earlier prototype) | After |
| - | - | - |
| ![Screenshot_20240630-172059_Trebuchet](https://github.com/CatimaLoyalty/Android/assets/1885159/859a1474-363e-4041-946c-dd5592d7b6f6) | ![Screenshot_20240630-172120_Trebuchet](https://github.com/CatimaLoyalty/Android/assets/1885159/4db64b2f-5c1f-4ec8-b13e-456bcb085c98) | ![Screenshot_20240630-172020_Trebuchet](https://github.com/Cati …
=> Allow store name thumbnails to span multiple lines

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/res/values/strings.xml
=> Support setting front or back image as thumbnail

CHANGELOG.md, app/src/main/res/layout/layout_chip_choice.xml
Fixes #1971 
| Light | Dark |
| - | - |
| ![Screenshot_20240722-194251_Trebuchet](https://github.com/user-attachments/assets/b1780cf2-19bb-4bef-b308-7f433c7abaa0) | ![Screenshot_20240722-194305_Trebuchet](https://github.com/user-attachments/assets/16eb6f87-4265-489c-9fe8-8b4d25ebbb18) |
=> Fix chip contrast in dark mode

.github/workflows/android.yml, app/build.gradle.kts, app/src/androidTest/java/protect/card_locker/MainActivitySearchViewTest.java, app/src/main/java/protect/card_locker/MainActivity.java
Fixes #1977.
On Android 13 and later with `android:enableOnBackInvokedCallback="true"`, for some reason pressing Back while the `SearchView` is open and the keyboard is shown simultaneously hides the keyboard and collapses the search view at the same time.
My solution is to set a listener to the menu item that hosts the `SearchView` that hides the keyboard if it's shown and prevents the item from being collapsed (it returns `false`). If the keyboard is hidden then the item is collapsed as normal (it returns `true`).
Alternatives I have tried:
- Remove `android:enableOnBackInvokedCallback="true"` (this is obviously a no go)
- On the [Google's website](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture#migrate-app), they mention this:
*You can register an …
=> Make Back button/gesture not instantly collapse the MainActivity's search view

app/src/main/java/protect/card_locker/BarcodeSelectorActivity.java, app/src/main/java/protect/card_locker/BarcodeValues.java, app/src/main/java/protect/card_locker/CardShortcutConfigure.java, app/src/main/java/protect/card_locker/CardsOnPowerScreenService.java, app/src/main/java/protect/card_locker/CatimaBarcode.java, app/src/main/java/protect/card_locker/DBHelper.java, app/src/main/java/protect/card_locker/LoyaltyCard.java, app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java, app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/MainActivity.java, app/src/main/java/protect/card_locker/ManageGroupCursorAdapter.java, app/src/main/java/protect/card_locker/ScanActivity.java, app/src/main/java/protect/card_locker/ShortcutHelper.java, app/src/main/java/protect/card_locker/Utils.java, app/src/main/java/protect/card_locker/importexport/CatimaExporter.java, app/src/test/java/protect/card_locker/ImportExportTest.java, app/src/test/java/protect/card_locker/LoyaltyCardCursorAdapterTest.java, app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java
This allows us to send any (partial) loyalty card into the edit activity, granting us greater flexibility in what kind of scan result we can parse
=> Refactor to allow updating a loyalty card from a bundle

app/src/main/java/protect/card_locker/ImportExportTask.java
Regression introduced in #1983. Fixes #2104.
Not completely happy with this but still an improvement.
The whole import/export flow needs to be completely redesigned still...
=> Don't show import cancelled text on import completion

app/src/main/java/protect/card_locker/MainActivity.java, app/src/test/java/protect/card_locker/MainActivityTest.java
Hello, 
In this pull request, I implemented functionality to save and restore the user's search query during screen rotations and enhance the user experience when navigating back from a selected card, the way user will have the query entered before saved and retrived, based on Issue #1962.
Unit tests were added and all four possible tests were run successfully without any error.
After hours of debugging I figured out the only way this Issue is solveble, where we need to implement 2 Strings to handle the changing text as input from user, because of the behaviour after coming back from a card regarding onQueryTextChange. (alternativelly we could use one string and one boolean for this very same behaviour) - changes in states were not effective on this Issue.
This approach is a bit …
=> #1962: Refactoring of Search Behavior: Restoring of Previous Search Query After Coming Back from Card Interaction or Screen Rotation on Search

app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java
This improves the display of high column counts
| - | - |
| ![Screenshot_20241111-174850_Trebuchet](https://github.com/user-attachments/assets/0863c524-afad-468e-9f86-5a8c7e8d24da) | ![Screenshot_20241111-174903_Trebuchet](https://github.com/user-attachments/assets/35a3106d-8e65-4fff-971e-35221aae647c) |
=> Use MEDIUM instead of FULL date format on main screen

app/src/main/res/layout/loyalty_card_layout.xml
This prevents cards with very long notes to take up the entire screen or more. This effect is worse with more columns.
=> Limit max line count to 5 on main view

docs/README.md
While I would still strongly recommend using IzzyOnDroid (it's faster, it uses my signing key so you can switch to the official build and are not locked into anything, among other benefits) over F-Droid, given Google's constant ramping-up of FOSS-dev-hostile policies, putting my eggs into more baskets seems still better.
Imho, the order of preference should be:
IzzyOnDroid > F-Droid > Google Play
(GitHub should only really be used for those who have other tools to watch GitHub for updates)
=> Re-add F-Droid

app/src/main/java/protect/card_locker/Utils.java
This severely reduces the risk of a transparent PNG being put on a background which is the same colour as the logo
It's not as advanced as planned, but this issue is really starting to get in my way with pkpass support (as many pkpass files contain transparent images) so I decided to opt for the quick fix.
Fixes #1972, fixes #1753
Here's a debug build if anyone wants to try before it goes live: [app-debug.zip](https://github.com/user-attachments/files/17961615/app-debug.zip) :)
=> Use black/white background colour instead of dominant colour for images

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
Commit 88c1dd1bc6cbc87a340693d5e5c7b86369f0b99d changed the behaviour of the background colour of the thumbnails, but the edit view still used the old behaviour. This creates more consistency.
Follow-up to #2201, which turned out to be incomplete.
=> Make thumbnails in edit view consistent with card view

.scripts/generate_feature_graphic/generate_feature_graphic.sh
Sans could be "friendlier". This also fixes the new zh-TW picture not showing up
=> Use Sans fonts for app name

.github/workflows/android.yml, .gitignore, app/build.gradle.kts, app/src/main/java/protect/card_locker/AboutActivity.java, app/src/main/java/protect/card_locker/Utils.java, build.sh, docs/RELEASE_STEPS.md
Currently, this just allows us to remove the donation button on Google Play without using the deprecated installer APIs.
In the future, this should allow us to also release multiple versions of Catima (for example: WearOS is a commonly requested feature, but this needs non-free dependencies, which may not be okay to all users).
=> Start using flavours

app/src/main/AndroidManifest.xml
Also cleans up some other unnecessary windowSoftInputMode configurations left over from years ago
Fixes #1967
=> Ensure save button stays pressable while keyboard is visible in edit screen

app/src/main/AndroidManifest.xml, app/src/main/java/protect/card_locker/MainActivity.java
K9 Mail/Thunderbird seems to use "application/vnd-com.apple.pkpass". This seems to be occasionally used online too (though much less commonly than "application/vnd.apple.pkpass"): https://github.com/thunderbird/thunderbird-android/pull/1358
=> Also parse application/vnd-com.apple.pkpass as pkpass files

app/src/main/AndroidManifest.xml, app/src/main/java/protect/card_locker/MainActivity.java
While espass files aren't pkpass files, they are so similar we can generally parse them fine with the pkpass parser. While this feature shouldn't be advertised as it is kinda hacky, it does make it easier for PassAndroid users to share cards with Catima users.
Helps with #2197, though not a real fix.
=> Add unofficial support for espass

app/build.gradle.kts, app/src/main/res/layout/barcode_selector_activity.xml, app/src/main/res/layout/import_export_activity.xml, app/src/main/res/layout/loyalty_card_view_layout.xml, app/src/main/res/layout/scan_activity.xml, app/src/main/res/values/themes.xml
This reverts commit https://github.com/CatimaLoyalty/Android/commit/ff08dbe5d53dea82ff8fd1a36796e9a56cca42d2.
I tried keeping the target at Android 15 and opting out of edge-to-edge
enforcement, but this is not a true compatibility mode and broke the
multi-selection UI in the main activity.
=> Revert to targeting Android 14

app/build.gradle.kts, app/src/main/java/protect/card_locker/BarcodeSelectorActivity.java, app/src/main/java/protect/card_locker/CardShortcutConfigure.java, app/src/main/java/protect/card_locker/CatimaAppCompatActivity.java, app/src/main/java/protect/card_locker/ImportExportActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/MainActivity.java, app/src/main/java/protect/card_locker/ManageGroupActivity.java, app/src/main/java/protect/card_locker/ManageGroupsActivity.java, app/src/main/java/protect/card_locker/ScanActivity.java, app/src/main/java/protect/card_locker/UCropWrapper.java, app/src/main/java/protect/card_locker/Utils.java, app/src/main/java/protect/card_locker/preferences/SettingsActivity.java, app/src/main/res/layout/group_main.xml, settings.gradle.kts
This also contains partial (but not complete) edge-to-edge support. Basically, whatever could easily support edge-to-edge had edge-to-edge added, but things that were too challenging were skipped for now.
TODO:
|                                            | Home | Scan | Barcode selector | View | Edit | Groups | Import/Export | Settings | About | Shortcut | Ucrop |
| ---------------------------------- | --------- | ------- | ------------------------ | ------- | ------ | ---------- | --------------------- | ------------ | --------- | ------------ | ---------- |
| 15 (gesture)                     | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | …
=> Target Android 15

app/src/main/java/protect/card_locker/BarcodeImageWriterTask.java, app/src/main/java/protect/card_locker/BarcodeSelectorAdapter.java, app/src/main/java/protect/card_locker/DBHelper.java, app/src/main/java/protect/card_locker/ImportURIHelper.java, app/src/main/java/protect/card_locker/LoyaltyCard.java, app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java, app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java, app/src/main/java/protect/card_locker/PkpassParser.kt, app/src/main/java/protect/card_locker/importexport/CatimaImporter.java, app/src/main/java/protect/card_locker/importexport/FidmeImporter.java, app/src/main/java/protect/card_locker/importexport/StocardImporter.java, app/src/main/java/protect/card_locker/importexport/VoucherVaultImporter.java, app/src/main/res/layout/loyalty_card_view_layout.xml, app/src/main/res/values/strings.xml, app/src/test/java/protect/card_locker/DatabaseTest.java, app/src/test/java/protect/card_locker/PkpassTest.kt
Hi, 
Reason, one of my cards is not able to be readed unless I shrink it to the half of the screen.
Maybe caused by a combination of old reader devices in the shop and own preference for landscape screen.
I see there is yet another MR from a couple of years ago, but it was hard to cope with Catima changes in the last 2 years, so I started fresh.
Thanks for considering.
Pere
=> Adding the ability to resize the width in the fullscreen view.

app/src/main/java/protect/card_locker/Utils.java
It's extremely hard to perfectly reach the 85.6:53.98 ratio, so if the image is cropped close enough to it, we enable center cropping. This allows a bit of the edges to be cut off to fully fill the image area.
Fixes #2248.
Debug build of commit e3e1e0c85b57852d772114bd7954a990eb249ed7: 
[app-foss-debug.zip](https://github.com/user-attachments/files/19895564/app-foss-debug.zip)
=> Fix icons having white/black lines

app/src/main/java/protect/card_locker/Utils.java
This PR improves performance by avoiding unnecessary resizing in  `resizeBitmap()` function when the image dimensions are already within the `maxSize` constraint.
This makes import handling of small images more efficient and avoids unnecessary memory use.
=> Optimize resizeBitmap(): Skip resizing for already-small images

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
Fixes #2431 
The keyboard will hide (if opened) on back pressed. Else dialog will appear.
=> Fix for save button being covered by keyboard

.scripts/generate_feature_graphic/featureGraphic.svg, .scripts/generate_feature_graphic/generate_feature_graphic.sh
- **kn-IN**: Fixed text overlaps in the feature graphic by moving the text up and ensuring proper font replacement.
- **ar**: Added Arabic to the language list for proper font replacement and RTL support.
- **he-IL**: Added Hebrew to the language list for proper font replacement.
=> Fix for minor issues with feature graphic generation
